spring:
  liquibase:
    change-log: classpath:/db/changelog/changelog.yaml
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5439/curency_db}
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: full
          permission-service:
            connect-timeout: 5000
logging:
  level:
    com.otp.curensyservis.feign.PermissionClient: DEBUG


